project:
  type: website

website:
  title: "Final project"
  navbar:
    left:
      - href: index.qmd
        text: Home Page
      - text: Data Analys
      - sources.qmd
      
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



